name: Build Release Assets
on:
  push:
    branches: ['*']
  workflow_dispatch:

env:
  CI_BLADEBIT: 1  # Our own CI, that is, not being built as a dependency

jobs:
  build-harvester-linux-arm64:
    runs-on: [ARM64, Linux]
    container:
      image: ghcr.io/chik-network/build-images/manylinux2014_cuda_aarch64:sha-e545a1e7e0dffb82a224518aa96424e665b848e5
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set Env
        uses: Chik-Network/actions/setjobenv@main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache DNF packages
        uses: actions/cache@v3
        with:
          path: /var/cache/dnf
          key: ${{ runner.os }}-dnf-${{ hashFiles('**/your-build-file') }}
          restore-keys: |
            ${{ runner.os }}-dnf-

      - name: Get Version Number
        id: version_number
        shell: bash
        run: ./.github/actions/get-version.sh centos arm64

      - name: Install Prerequisites
        shell: bash
        run: |
          set -eo pipefail
          export module_platform_id=platform:el9
          export MODULE_PLATFORM_ID=platform:el9
          export PLATFORM_ID=platform:el9
          uname -a
          cat /etc/os-release
          yum install -y dnf
          dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
          dnf install -y dnf-plugins-core
          dnf makecache
          dnf install -y kernel-headers.aarch64 kernel-devel.aarch64 tar bzip2 make automake gcc gcc-c++ pciutils elfutils-libelf-devel libglvnd-opengl libglvnd-glx libglvnd-devel acpid pkgconfig dkms
          dnf install -y cmake
          dnf group install -y "Development Tools"
          dnf install -y gmp-devel numactl-devel make git wget sed

      - name: Build Harvester
        shell: bash
        run: |
          export artifact_name="green_reaper-v${{ env.BB_VERSION }}-linux-ARM64.tar.gz"
          echo "harvester_artifact_name=${artifact_name}" >> "$GITHUB_ENV"
          # emits env.harvester_artifact_path
          bash .github/actions/build-harvester.sh --artifact "${artifact_name}"

      - name: Upload Harvester Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.harvester_artifact_name }}
          path: ${{ env.harvester_artifact_path }}
          if-no-files-found: error

  build-bladebit-centos-arm64:
    runs-on: [ARM64, Linux]
    container:
      image: quay.io/centos/centos:stream8
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set Env
        uses: Chik-Network/actions/setjobenv@main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Version Number
        id: version_number
        run: .github/actions/get-version.sh centos arm64

      - name: Install Prerequisites
        run: |
          dnf install -y gcc-toolset-9-gcc gcc-toolset-9-gcc-c++ \
            cmake gmp-devel numactl-devel make git

      - name: Build
        run: |
          source /opt/rh/gcc-toolset-9/enable
          .github/actions/build-asset-unix.sh --artifact ${{ env.BB_ARTIFACT_NAME }} --version ${{ env.BB_VERSION }}

      - name: Upload Artifact CentOS ARM64
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BB_ARTIFACT_NAME }}
          path: ${{ github.workspace }}/bin/${{ env.BB_ARTIFACT_NAME }}
          if-no-files-found: error
